const FONTS = {
    WorkSansBlack: "WorkSans-Black",
    WorkSansBlackItalic: "WorkSans-BlackItalic",
    WorkSansBold: "WorkSans-Bold",
    WorkSansBoldItalic: "WorkSans-BoldItalic",
    WorkSansExtraBold: "WorkSans-ExtraBold",
    WorkSansExtraBoldItalic: "WorkSans-ExtraBoldItalic",
    WorkSansExtraLight: "WorkSans-ExtraLight",
    WorkSansExtraLightItalic: "WorkSans-ExtraLightItalic",
    WorkSansItalicVariableFont_wght: "WorkSans-Italic-VariableFont_wght",
    WorkSansItalic: "WorkSans-Italic",
    WorkSansLight: "WorkSans-Light",
    WorkSansLightItalic: "WorkSans-LightItalic",
    WorkSansMedium: "WorkSans-Medium",
    WorkSansMediumItalic: "WorkSans-MediumItalic",
    WorkSansRegular: "WorkSans-Regular",
    WorkSansSemiBold: "WorkSans-SemiBold",
    WorkSansSemiBoldItalic: "WorkSans-SemiBoldItalic",
    WorkSansThin: "WorkSans-Thin",
    WorkSansThinItalic: "WorkSans-ThinItalic",
    WorkSansVariableFont_wght: "WorkSans-VariableFont_wght",
    MontserratBlack: "Montserrat-Black",
    MontserratBlackItalic: "Montserrat-BlackItalic",
    MontserratBold: "Montserrat-Bold",
    MontserratBoldItalic: "Montserrat-BoldItalic",
    MontserratExtraBold: "Montserrat-ExtraBold",
    MontserratExtraLight: "Montserrat-ExtraLight",
    MontserratExtraLightItalic: "Montserrat-ExtraLightItalic",
    MontserratItalic: "Montserrat-Italic",
    MontserratLight: "Montserrat-Light",
    MontserratLightItalic: "Montserrat-LightItalic",
    MontserratMediumItalic: "Montserrat-MediumItalic",
    MontserratRegular: "Montserrat-Regular",
    MontserratSemiBold: "Montserrat-SemiBold",
    MontserratSemiBoldItalic: "Montserrat-SemiBoldItalic",
    MontserratThin: "Montserrat-Thin",
    MontserratMedium: "Montserrat-Medium",
  };
  export default FONTS;
  
