const IMAGES = {
  HOME_TAB_IMG: require('../assets/Images/TabBarImages/home/home.png'),
  FEED_TAB_IMG: require('../assets/Images/TabBarImages/feed/feed.png'),
  REFERRAL_TAB_IMG: require('../assets/Images/TabBarImages/referrals/referrals.png'),
  WALLET_TAB_IMG: require('../assets/Images/TabBarImages/Wallet/Wallet.png'),
  PROFILE_TAB_IMG: require('../assets/Images/TabBarImages/profile/profile.png'),
  LP_IMG: require('../assets/Images/ProfileImages/lp/lp.png'),
  LUCKYDIEM_IMG: require('../assets/Images/ProfileImages/luckyDiem/luckyDiem.png'),
  NOTIFICATION_IMG: require('../assets/Images/ProfileImages/notification/notification.png'),
  VETERANCLUB_IMG: require('../assets/Images/ProfileImages/veteranClub/veteranClub.png'),
  FRIENDONE_IMG: require('../assets/Images/Friends/friendone/friendone.png'),
  FRIENDSECOND_IMG: require('../assets/Images/Friends/friendsecond/friendsecond.png'),
  FRIENDTHIRD_IMG: require('../assets/Images/Friends/friendthird/friendthird.png'),
  FRIENDFOURTH_IMG: require('../assets/Images/Friends/friendfourth/friendfourth.png'),
  FRIENDFIVTH_IMG: require('../assets/Images/Friends/friendfifth/friendfifth.png'),
  BRONZE_IMG: require('../assets/Images/LoyaltyClubs/bronze/bronze.png'),
  SILVER_IMG: require('../assets/Images/LoyaltyClubs/silver/silver.png'),
  GOLD_IMG: require('../assets/Images/LoyaltyClubs/gold/gold.png'),
  PLATINUM_IMG: require('../assets/Images/LoyaltyClubs/platinum/platinum.png'),
  DIAMOND_IMG: require('../assets/Images/LoyaltyClubs/diamond/diamond.png'),
  MYSTATEMENT_IMG: require('../assets/Images/OtherProfileImge/myStatement/myStatement.png'),
  MYPOST_IMG: require('../assets/Images/OtherProfileImge/myPost/myPost.png'),
  MANAGECARD_IMG: require('../assets/Images/OtherProfileImge/manageCard/manageCard.png'),
  LEADERBOARD_IMG: require('../assets/Images/OtherProfileImge/leaderBoard/leaderBoard.png'),
  COINCOUNT_IMG: require('../assets/Images/OtherProfileImge/coinCount/coinCount.png'),
  BADGES_IMG: require('../assets/Images/OtherProfileImge/badges/badges.png'),
  ACCOUNTSETTING_IMG: require('../assets/Images/OtherProfileImge/accountSetting/accountSetting.png'),
  EDIT_IMG: require('../assets/Images/OtherProfileImge/editIcon/editIcon.png'),
  RIGHT_ARRAOW_IMG: require('../assets/Images/OtherProfileImge/rightArrow/rightArrow.png'),
};

export default IMAGES;
